### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by mustafashabib** [aws/aws-flow-ruby#104]
Hey All

Can we get some guidance on how people are testing their workflows and activities? I can't seem to find much in the way of examples or docs around this topic for the Ruby framework.

[Cross posted at stackoverflow](http://stackoverflow.com/questions/33291386/unit-testing-aws-swf-ruby-flow) in case you want to answer there instead.

Thanks
-m

**Comment by runjoerun** [comment]
+1

**Comment by mjsteger** [comment]
I would definitely test the activities separate from everything else, as they should be treatable as independent units. For the decider parts, you have two choices: you can test them against the live SWF system, or against a mocked up set of events that have happened to ensure it will take the correct path. The former option will incur some costs and means your tests will have to be fault tolerant and withstand some timing variance), while the latter will be a lot more upfront work and is pretty brittle. [Here's an example](https://github.com/mjsteger/aws-flow-ruby/blob/master/aws-flow/spec/aws/decider/integration/integration_spec.rb#L1282) of the live test and [here is an example](https://github.com/aws/aws-flow-ruby/blob/master/aws-flow/spec/aws/decider/unit/decider_spec.rb#L1452) of setting up the mocking path. If you are trying to add regression tests/figure out what just happened in a workflow that failed, you might want to look at the [workflow replayer](https://github.com/aws/aws-flow-ruby/blob/master/aws-flow/lib/aws/replayer.rb#L1).

This stuff should definitely be better documented, and I think it might make sense to have a more simplified/improved way to add regression tests without needing to interact with the service, in particular probably from the WorkflowReplayer. It's something I'll work on in the near future.

So, all told, if you can afford it, I'd recommend going with the live tests for general coverage, and making sure you see the results you desire(i.e. "these activities finished successfully, and the workflow gave back such and such a value"). If you are attempting to debug a problem which already occurred, or especially one which occurs sporadically, WorkflowReplayer and testing with mocks are the way to go.

**Comment by mustafashabib** [comment]
Thanks @mjsteger - much appreciated.
