### ISSUE TITLE
error handling with async activity, wait_for_all does not wait

### ISSUE THREAD

**Issue by jongbeau** [aws/aws-flow-ruby#24]
When using the error_handler pattern to capture exceptions in async activities, wait_for_all stops working. 

I'm following the pattern documented here: (http://docs.aws.amazon.com/amazonswf/latest/awsrbflowguide/programming-error-handling.html)

Simple example:
    futures = []
    error_handler do |t|
      t.begin {
        futures << activity.send_async(:run_activity1, arg)
        futures << activity.send_async(:run_activity2, arg)
      }
      t.rescue(Exception) do |error|
        # Do something with the error
      end
    end
    wait_for_all(futures)

In this example, wait_for_all does not wait for the async activities. If I remove the error_handler block, the wait works as expected.  How can I use error handling with async activities and wait?

**Comment by jcavalieri** [comment]
I think this means the pick_first_branch_workflow sample is a bad example then. Probably should be update to include what was posted here as a solution.

**Comment by jcavalieri** [comment]
Something smells about that workaround too. Maybe the async error handler should not be for an entire block but be per future.
