### ISSUE TITLE
[Enhancement] Need blocking fork option

### ISSUE THREAD

**Issue by BiggerNoise** [aws/aws-flow-ruby#7]
Right now the workers can either use forking or not.  Unfortunately, when using the forking option, the worker immediately polls for the next task and forks it, and so on.

Unfortunately, when a Ruby worker allocates memory, it's never really returned to the OS, so we would like to fork the workers so that memory is returned when the forked process exits.

However, we can't use the user_forking option because it will keep stacking up fairly complex tasks.

What I would like is a blocking fork: the work is executed in a fork, but the poll loop doesn't continue until the fork exits.

**Comment by ishanm** [comment]
@arkadiyt Was wondering if you guys ever figured out a way to solve this? (sorry, I know this is a really old thread)

**Comment by arkadiyt** [comment]
Not that I recall - we're no longer using Simple Workflow

**Comment by ishanm** [comment]
Cool thanks
