### ISSUE TITLE
ActivityTimeOutException not retried with ruby 2.1

### ISSUE THREAD

**Issue by nerdyworm** [aws/aws-flow-ruby#70]
Hello friends!

I'm sure we are doing something wrong but...

The following hunk of code works correctly with ruby 2.0.0.  The activity is retried until the workflow times out which is what I expect to happen.  Moving to ruby 2.1.0 the activity is never retried and the workflow's execution is failed after the activity time out occurs.

Gem version are aws-sdk 1.56.0 and aws-flow 2.0.2

Thanks in advance for any advice :heart:

Link to hunk of code:
https://gist.github.com/nspence/3f1079b96086ce2af4f7

**Comment by pmohan6** [comment]
The latest release should have the fix. Sorry about the delay in pushing it out.

**Comment by nspence** [comment]
Glad to hear it! We'll be trying it out shortly.
