### ISSUE TITLE
Runner leaves running worker processes

### ISSUE THREAD

**Issue by kalpitad** [aws/aws-flow-ruby#78]
My test process for my workflows and activities involves starting the runner, finding a bug, killing the runner, re-starting the runner, finding a bug, and repeat.  I'm using ctrl+c to kill the runner each time and I've noticed two problems with this:

1) The worker processes stick around and keep running.

![screenshot](https://cloud.githubusercontent.com/assets/4335348/5062540/8ce3a536-6d79-11e4-9e57-846ee5a15701.png)

2) Once I had enough orphaned workers running on my box, I noticed that they would often pick up tasks in the task list instead of the workers started by my most recent start of the runner. This would result in the workflow timing out and I wouldn't get to test out my new code.

Is this a bug in the runner, or is there a more appropriate way to stop the runner so that the clean up code (which I can see in the source) gets called. Thanks!

**Comment by kalpitad** [comment]
Hi @pmohan6 - I'm so sorry, I didn't see your request until now. I remember what the names were... If I'm able to repro this, I will definitely share what I learn with you. Thanks for clarifying how many processes I should see. I will share if this is not the case when I next work on my workflows. Thanks again!

**Comment by pmohan6** [comment]
Resolving this issue since we haven't seen a repro. Feel free to reopen if you have any further comments.
