### ISSUE TITLE
Basic usage example doesn't work (missing version in activity definition?)

### ISSUE THREAD

**Issue by mojodna** [aws/aws-flow-ruby#88]
From the SWF console:

```
This activity worker was told to work on activity type <AWS::SimpleWorkflow::ActivityType domain:FlowDefault name:MyJobs.hello version:1.0>, but this activity worker only knows how to work on MyJobs.hello
```

This is with 2.2.0:

```bash
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
```

**Comment by mojodna** [comment]
This also works with 2.1.5:

```bash
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]
```

**Comment by pmohan6** [comment]
We recently saw this issue as well. We will be releasing a fix for this soon. Thanks for reporting it.

**Comment by pas256** [comment]
Any update on this one?

**Comment by pmohan6** [comment]
I'm still working on this issue. I'm trying to figure out what changed in ruby >= 2.2.0. We haven't changed the Workflow or Activity workers that should cause this issue.
Look at the following snippet (The task handler [1] looks for the workflow definition when it receives a DecisionTask). It looks like the workflow definition map contains the correct workflow type object but for some reason ruby hash lookup is failing.
```
[7] pry(#<AWS::Flow::DecisionTaskHandler>)> @workflow_definition_map[workflow_type]
=> nil
[8] pry(#<AWS::Flow::DecisionTaskHandler>)> @workflow_definition_map.keys.first.eql?(workflow_type)
=> true
......
[10] pry(#<AWS::Flow::DecisionTaskHandler>)> workflow_type.hash
=> -1381388215588935896
[11] pry(#<AWS::Flow::DecisionTaskHandler>)> @workflow_definition_map.keys.first.hash
=> -1381388215588935896
```

[1] https://github.com/aws/aws-flow-ruby/blob/master/aws-flow/lib/aws/decider/task_handler.rb#L75

**Comment by Vaguery** [comment]
Even the Hello World example doesn't seem to work, with the analogous error message.

~~~ text
This activity worker was told to work on activity type <AWS::SimpleWorkflow::ActivityType domain:FlowDefault name:HelloWorld.hello version:1.0>, but this activity worker only knows how to work on HelloWorld.hello
~~~

**Comment by Vaguery** [comment]
Aha hang on: is `workflow_type` a `String`?

Might this have something to do with the [auto-freezing of Ruby `Strings` when they're used as `Hash` keys, since 2.1?](http://globaldev.co.uk/2014/05/ruby-2-1-in-detail/)

**Comment by pmohan6** [comment]
workflow_type is an object of type AWS::SimpleWorkflow::WorkflowType but it's attributes like @name and @version are strings. We override it's hash and eql? function [internally here](https://github.com/aws/aws-flow-ruby/blob/master/aws-flow/lib/aws/decider/worker.rb#L74). I've a feeling it's something to do with that.

Although, this started happening ruby 2.2 onwards. AFAICT, it works fine with versions < 2.2.

**Comment by Vaguery** [comment]
I hate to ask something so trivial, since I'm unfamiliar with the codebase, but are both `eql?` and `hash` defined correctly for `AWS::SimpleWorkflow::WorkflowType`?

**Comment by pmohan6** [comment]
I don't see anything wrong with eql? and hash. The two type objects should be logically equivalent if the their name and version (which are both strings) are equal. Do you see anything wrong with the implementation?

Also, after digging more into it today, it looks like the workflow_type objects are getting mutilated somewhere internally because rehashing the ```@workflow_definition_map``` in [task_handler.rb#75](https://github.com/aws/aws-flow-ruby/blob/master/aws-flow/lib/aws/decider/task_handler.rb#L75) seems to be fixing this issue -
```ruby
@workflow_definition_map.rehash
workflow_definition_factory = @workflow_definition_map[workflow_type]
```
It looks very similar to issues related to auto-freezing of strings when used as hash keys.

**Comment by pmohan6** [comment]
On second thought, I think you are right.

Ruby introduced Symbol GC in 2.2. The ```hash``` and ```eql?``` functions generate dynamic symbols and use those to calculate the hash value or compare equality respectively. These dynamic symbols will get GC-ed and will result in different hash values each time!

```ruby
[23] pry(#<AWS::Flow::DecisionTaskHandler>)> GC.start
=> nil
[24] pry(#<AWS::Flow::DecisionTaskHandler>)> workflow_type.hash
=> -573381024770253200
[25] pry(#<AWS::Flow::DecisionTaskHandler>)> GC.start
=> nil
[26] pry(#<AWS::Flow::DecisionTaskHandler>)> workflow_type.hash
=> -1547868217118247477
```

**Comment by pmohan6** [comment]
https://github.com/aws/aws-flow-ruby/commit/f923dc1012383492732cddbdec02347d3bf24da1

**Comment by davidcpell** [comment]
Sorry to comment on a closed ticket but this is the only thing that seemed relevant when I googled my problem. I'm getting this same error.

```
<AWS::SimpleWorkflow::ActivityType domain:cicada-flow-david name:Activity.fetch version:0.1> failed with exception: #<
RuntimeError: This activity worker was told to work on activity type <AWS::SimpleWorkflow::ActivityType domain:my-domain name:Activity.fetch version:0.1>, but this 
activity worker only knows how to work on ... Activity.fetch Activity.foo Activity.bar ... FlowDefaultResultActivityRuby.run>
```

As you can see, it's saying that running the `Activity.fetch` activity failed, but `Activity.fetch` is listed in the acitivities that the worker knows how to work on.

Am I missing something here...?
