### ISSUE TITLE
Generated file encodings confuse Ruby

### ISSUE THREAD

**Issue by mojodna** [aws/aws-flow-ruby#89]
```bash
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
$ aws-flow-utils -c local -n Booking
---
Your AWS Flow Framework for Ruby application will be located at: /Users/seth/src/tmp/aws-flow-ruby/Booking/
---
```

Following this, I pasted in the Booking sample from http://docs.aws.amazon.com/amazonswf/latest/awsrbflowguide/basic-workflow.html (2 nits in those docs: the second `activities.rb` should be `workflows.rb`, `worker.rb` should be `worker.json`).  vim says that the file encoding is `mac` while open.  Attempting to run it results in:

```
$ aws-flow-ruby -f worker.json
/Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:95:in `const_get': uninitialized constant BookingActivities (NameError)
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:95:in `block in get_classes'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:95:in `map!'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:95:in `get_classes'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:194:in `block in start_activity_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:187:in `each'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:187:in `start_activity_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:312:in `start_workers'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:406:in `run'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/lib/aws/runner.rb:424:in `main'
	from /Users/seth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/aws-flow-3.0.0/bin/aws-flow-ruby:5:in `<top (required)>'
	from /Users/seth/src/tmp/aws-flow-ruby/aws-flow/aws-flow-ruby:16:in `load'
	from /Users/seth/src/tmp/aws-flow-ruby/aws-flow/aws-flow-ruby:16:in `<main>'
```

Changing the file encoding (`:set fileencoding=unix`) and saving allows the workflow to start.

**Comment by EronHennessey** [comment]
Hi, I'm currently updating that page with corrected instructions, thanks!  I'll also try to get those file encodings fixed for the samples, as well.

**Comment by EronHennessey** [comment]
Hi again, could you tell me what file are you referring to that has mac file encoding, btw?  I looked at [runner.rb](https://github.com/aws/aws-flow-ruby/blob/master/aws-flow/lib/aws/runner.rb) in and it looks like it has standard unix endings.

**Comment by mojodna** [comment]
They were the files that were generated by `aws-flow-utils`.

**Comment by EronHennessey** [comment]
Ah, interesting--on my Ubuntu installation, it generates unix line endings. Are you running the utility on a Mac?

**Comment by mojodna** [comment]
Yes.  Huh.

**Comment by EronHennessey** [comment]
Yes, it seems to be using the default line endings for the platform on which it's being run. I've brought the issue up with the team. Thanks again for the info!

**Comment by pmohan6** [comment]
I've a fix ready for this. Will release the patch soon.

**Comment by pmohan6** [comment]
https://github.com/aws/aws-flow-ruby/commit/4fd7c50a04af1c28b6666a1408d25aa77a1d79fe
