### ISSUE TITLE
error_handler doesn't seem to work

### ISSUE THREAD

**Issue by mojodna** [aws/aws-flow-ruby#91]
Tested on Ruby 2.1.5, 2.0.0-p643, 1.9.3-p551 (all via `rbenv` on OS X 10.9.5).

`SplitMergeActivity.noop` is a registered activity (and split/merge is a misnomer, but that's where I started), but I'm not including it (it just returns its input), as the workflow never gets past `DecisionTaskStarted` except to timeout.

The output from the workflow below looks like:

```
input: 5
sending 0
6
7
x:
1
```

...which suggests that the body of the `error_handler` block is running on another thread / fiber (ok, so things move into the `t.ensure` block).  However, the `t.begin` block never appears to execute (and exceptions are swallowed by the framework, so they're only visible in the SWF console (not locally) _if_ the `DecisionTask` actually fails (vs. timing out)).

What am I doing wrong?

`workflow.rb`:

```ruby
require "aws/decider"

DOMAIN = "SplitMerge"
WF_TASKLIST = "splitmerge_workflow_tasklist"

class SplitMergeWorkflow
  extend AWS::Flow::Workflows

  version "1.4"

  activity_client(:client) do |options|
    options.version = "1.4"
    options.default_task_list = "splitmerge_activity_tasklist"
    options.default_task_heartbeat_timeout = 60
    options.default_task_start_to_close_timeout = 120
    options.prefix_name = "SplitMergeActivity"
  end

  entry_point :start

  def start(input)
    puts "input: #{input}"

    results = []

    i = 0
    
    puts "sending #{i}"
    error_handler do |t|
      puts "1"
      t.begin do
        puts "2"
        results << client.send_async(:noop, i)
      end

      t.rescue AWS::Flow::ActivityTaskTimedOutException do |e|
        puts "3" 
        puts "attempt #{i} timed out: #{e}"
      end
      t.rescue ActivityTaskFailedException do |e|
        puts "4"
        puts "attempt #{i} failed: #{e}"
      end
      t.ensure do
        puts "5"
        puts "ensure"
      end
    end

    puts "6"

    wait_for_all(results)

    x = results.map(&:get).join(",")

    puts "x: #{x}"

    x
  end
end

if $0 == __FILE__
  swf = AWS::SimpleWorkflow.new
  domain = swf.domains[DOMAIN]
  swf.domains.create(DOMAIN, 10) unless domain.exists?

  worker = AWS::Flow::WorkflowWorker.new(domain.client, domain, WF_TASKLIST, SplitMergeWorkflow)
  worker.register
  worker.start
end
```

`starter.rb`:

```ruby
require "aws/decider"

require "./workflow"

swf = AWS::SimpleWorkflow.new
domain = swf.domains[DOMAIN]
swf.domains.create(DOMAIN, 10) unless domain.exists?

client = AWS::Flow.workflow_client(domain.client, domain) do |options|
  options.workflow_name = "SplitMergeWorkflow"
  options.execution_start_to_close_timeout = 600
  options.task_list = WF_TASKLIST
  options.task_start_to_close_timeout = 300
  options.child_policy = :request_cancel
end

client.start_execution(5)
```

**Comment by pmohan6** [comment]
Apologies for the late reply. Looks like the error that you are seeing is because of the following line -
```ruby
t.rescue ActivityTaskFailedException do |e|
```
ActivityTaskFailedException is not included in the top level module. You must explicitly rescue AWS::Flow::ActivityTaskFailedException or include the module AWS::Flow.

Also, you can see workflow logs at - /tmp/AWS-Flow-WorkflowWorker. They will contain the error messages when your decider is not able to make decisions and/or reply back to the service.

**Comment by mojodna** [comment]
Ah, that makes total sense.  You might want to add a reference to the workflow logs in the README--I was looking for some sort of output like that (because errors seemed to be swallowed otherwise) and never found it.

Thanks!

**Comment by pmohan6** [comment]
Thanks for the feedback! We will definitely look into adding more information about the logs.
