### ISSUE TITLE
Activity worker can't listen to a non-default task list

### ISSUE THREAD

**Issue by grantr** [aws/aws-flow-ruby#92]
Say I want to send a particular activity to multiple task lists. The same activity needs to execute in multiple worker pools, and I want to wait for all of those pools to finish before proceeding.

I tried modifying the booking example at https://github.com/awslabs/aws-flow-ruby-samples/blob/master/samples/booking/flow/workflows.rb#L31 to specify a non-default task list when enqueueing `reserve_car` tasks:

```ruby
futures << client.send_async(:reserve_car, options[:request_id]) {{ :task_list => "booking_activity_reserve_car1" }}
futures << client.send_async(:reserve_car, options[:request_id]) {{ :task_list => "booking_activity_reserve_car2" }}
```

And I created a new worker.json from https://github.com/awslabs/aws-flow-ruby-samples/blob/master/samples/booking/worker.json that looks like this:

```json
{
  "domain":
    {
      "name": "Booking",
      "retention_in_days": 10
    },
  "activity_workers": [
    {
      "number_of_workers": 5,
      "number_of_forks_per_worker": 10,
      "task_list": "booking_activity_reserve_car1"
    }
  ]
}
```

Plus a similar one for `booking_activity_reserve_car2`.

So for this example I want one worker to process tasks in the default task list, and two other workers to process `reserve_car1` and `reserve_car2`. The point is to demonstrate that the task_list for an activity can be decided at runtime.

When I run the `reserve_car` workers, there seems to be no way to avoid this error:

```
gems/aws-flow-3.0.0/lib/aws/decider/worker.rb:348:in `rescue in block in register': Activity [BookingActivity.send_confirmation]: There is a difference between the types you have registered previously and the types you are currently registering, but you haven't changed the version. These new changes will not be picked up. In particular, these options are different {:default_task_list=>{:name=>"booking_activity_reserve_car1"}} (RuntimeError)
```

It seems like there's no way to run a worker that listens to a non-default task list.

**Comment by grantr** [comment]
This seems to be a limitation of the runner (https://github.com/aws/aws-flow-ruby/blob/master/aws-flow/lib/aws/runner.rb#L109) which assumes that every worker needs to register its tasks. The file_processing sample (https://github.com/awslabs/aws-flow-ruby-samples/tree/9857169db9066522045da145cc428ba18afbcd13/samples/file_processing) uses host-specific task lists without the runner, perhaps because of this issue?

**Comment by pmohan6** [comment]
If you don't specify a value for default_task_list in code, then a reserved string "USE_WORKER_TASK_LIST" is assumed to be the default. This string instructs the ActivityWorkers to register the activity type with the tasklist that they are asked to work on. So, in your case, one set of workers was trying to register the activity type with tasklist 'booking_activity_reserve_car1' and another set with tasklist 'booking_activity_reserve_car2'.

You can get around this issue by specifying the default_task_list for the activity like so [1] -
```ruby
  activity :reserve_car do
    {
      version: "1.0",
      default_task_list: "booking_activities"
    }
  end
```

We will try to improve our documentation to prevent this confusion in the future.

[1] https://github.com/awslabs/aws-flow-ruby-samples/blob/master/samples/booking/flow/activities.rb

**Comment by pmohan6** [comment]
Resolving the issue. Feel free to reopen if you have any further questions.
